<?php
// licensed under GPL v2. (C) 2008 Ace Suares, Willemstad
	/*
		Copyright (C) 2008 Ace Suares, Gravenstraat 4, Otrobanda, Willemstad, Curaçao, Nehterlands Antilles
		http://www.suares.com
		
		This program is free software; you can redistribute it and/or modify
		it under the terms of the GNU General Public License as published by
		the Free Software Foundation; either version 2 of the License, or
		(at your option) any later version.
		
		This program is distributed in the hope that it will be useful,
		but WITHOUT ANY WARRANTY; without even the implied warranty of
		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
		GNU General Public License for more details.
		
		You should have received a copy of the GNU General Public License
		along with this program; if not, write to the Free Software
		Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
	*/
			// strange exception
/*
				switch ( strtolower( $gemeente_naam ) ):
					case "oegstgeest" :
						$kaart_x = 146;
						$kaart_y = 228;
					break;
					case "millingen aan de rijn" :
						$kaart_x = 309;
						$kaart_y = 281;
					break;
					case "hardinxveld-giessendam" :
						$kaart_x = 191;
						$kaart_y = 284;
					break;
					case "lelystad" :
						$kaart_x = 243;
						$kaart_y = 182;
					break;
					case "enkhuizen" :
						$kaart_x = 228;
						$kaart_y = 141;
					break;
					case "reimerswaal" :
						$kaart_x = 107;
						$kaart_y = 350;
					break;
					case "wieringen" :
						$kaart_x = 199;
						$kaart_y = 111;
					break;
					case "goedereede" :
						$kaart_x = 98;
						$kaart_y = 287;
					break;
					case "amerongen" :
						$kaart_x = 248;
						$kaart_y = 260;
					break;
					case "bloemendaal" :
						$kaart_x = 158;
						$kaart_y = 192;
					break;
					case "eersel" :
						$kaart_x = 234;
						$kaart_y = 363;
					break;
					case "heerenveen" :
						$kaart_x = 304;
						$kaart_y = 105;
					break;
					case "hendrik-ido-ambacht" :
						$kaart_x = 160;
						$kaart_y = 284;
					break;
					case "jacobswoude" :
						$kaart_x = 168;
						$kaart_y = 225;
					break;
					case "rotterdam" :
						$kaart_x = 149;
						$kaart_y = 270;
					break;
					case "twenterand" :
						$kaart_x = 366;
						$kaart_y = 184;
					break;
					case "winsum" :
						$kaart_x = 349;
						$kaart_y = 47;
					break;
				endswitch;
*/
?>
