<?php
			// strange exception
				switch ( strtolower( $gemeente_naam ) ):
					case "oegstgeest" :
						$kaart_x = 146;
						$kaart_y = 228;
					break;
					case "millingen aan de rijn" :
						$kaart_x = 309;
						$kaart_y = 281;
					break;
					case "hardinxveld-giessendam" :
						$kaart_x = 191;
						$kaart_y = 284;
					break;
					case "lelystad" :
						$kaart_x = 243;
						$kaart_y = 182;
					break;
					case "enkhuizen" :
						$kaart_x = 228;
						$kaart_y = 141;
					break;
					case "reimerswaal" :
						$kaart_x = 107;
						$kaart_y = 350;
					break;
					case "wieringen" :
						$kaart_x = 199;
						$kaart_y = 111;
					break;
					case "goedereede" :
						$kaart_x = 98;
						$kaart_y = 287;
					break;
					case "amerongen" :
						$kaart_x = 248;
						$kaart_y = 260;
					break;
					case "bloemendaal" :
						$kaart_x = 158;
						$kaart_y = 192;
					break;
					case "eersel" :
						$kaart_x = 234;
						$kaart_y = 363;
					break;
					case "heerenveen" :
						$kaart_x = 304;
						$kaart_y = 105;
					break;
					case "hendrik-ido-ambacht" :
						$kaart_x = 160;
						$kaart_y = 284;
					break;
					case "jacobswoude" :
						$kaart_x = 168;
						$kaart_y = 225;
					break;
					case "rotterdam" :
						$kaart_x = 149;
						$kaart_y = 270;
					break;
					case "twenterand" :
						$kaart_x = 366;
						$kaart_y = 184;
					break;
					case "winsum" :
						$kaart_x = 349;
						$kaart_y = 47;
					break;
				endswitch;

?>
