<?

// new style init

$WebEngine_version="2.64";

$WebEngine_sitename="Duurzaamheidsspiegel Beheer";

$WebEngine_host="127.0.0.1:3306";

$WebEngine_database="la21nl2002";

$WebEngine_admin_user="la21nl2002RO";

$WebEngine_admin_password="jjjrjje993mmdsjdjj";

$WebEngine_regular_user="";

$WebEngine_regular_password="";

$WebEngine_magic="KKkLmjd783hhjdhjkk";

$Webengine_include_path="/usr/local/webengine/" . $WebEngine_version . "/";

$Webengine_local_inc = $Webengine_include_path . "local.inc";

$WebEngine_debug = "";


$dblink=mysql_connect($WebEngine_host,$WebEngine_admin_user,$WebEngine_admin_password);

$font="Verdana, Arial";
$small_font=   "<FONT FACE=\"$font\" SIZE=1>";
$base_font=    "<FONT FACE=\"$font\" SIZE=2>";
$big_font=     "<FONT FACE=\"$font\" SIZE=3>";
$very_big_font="<FONT FACE=\"$font\" SIZE=4>";

?>